"""Add restrict_to_knowledge

Revision ID: bc21511bb54b
Revises: aa70707daabf
Create Date: 2026-01-21 05:06:12.153890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc21511bb54b'
down_revision: Union[str, None] = 'aa70707daabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_configs', sa.Column('restrict_to_knowledge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_configs', 'restrict_to_knowledge')
    # ### end Alembic commands ###
